###############################################################################
# GenieACS – serviços principais                                              #
###############################################################################
services:
  genieacs:
    image: drumsergio/genieacs:latest
    container_name: genieacs
    restart: always
    depends_on:
      - mongo
    environment:
      GENIEACS_UI_JWT_SECRET: changeme
      GENIEACS_MONGODB_CONNECTION_URL: mongodb://mongo/genieacs?authSource=admin
      DEBUG: "cwmp:*"
    # UI/NBI/FS apenas no host local (seguro). CWMP NÃO é exposto publicamente.
    ports:
      - "127.0.0.1:3000:3000"   # Interface Web (somente local)
      - "127.0.0.1:7557:7557"   # NBI – REST API (somente local)
      - "127.0.0.1:7567:7567"   # File-Server (somente local)
    expose:
      - "7547"                  # CWMP visível só na rede Docker (para o ngrok)
    networks:
      - genieacs_net

  mongo:
    image: mongo:8.0
    container_name: mongo-genieacs
    restart: always
    volumes:
      - data_db:/data/db
      - data_configdb:/data/configdb
    expose:
      - "27017"
    networks:
      - genieacs_net

  #############################################################################
  # Simulador CPE – 5 roteadores no mesmo contêiner                           #
  #############################################################################
  genieacs-sim:
    image: drumsergio/genieacs-sim:latest
    container_name: genieacs-sim
    depends_on:
      - genieacs
    command: >-
      genieacs-sim --processes 5 --serial 100 --acs-url http://genieacs:7547
    restart: always          # mantém simuladores vivos em reinício
    networks:
      - genieacs_net

  genieacs-mcp:
    image: drumsergio/genieacs-mcp:latest
    container_name: genieacs-mcp
    depends_on:
      - genieacs
    environment:
      ACS_URL:  http://genieacs:7557
      ACS_USER: admin
      ACS_PASS: admin
    ports:
      - "127.0.0.1:8080:8080"   # painel do MCP só local
    networks:
      - genieacs_net

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.backend
    container_name: genieacs-backend
    restart: always
    depends_on:
      - genieacs
    environment:
      GENIEACS_NBI_URL: http://genieacs:7557
      ACS_API_KEY_FILE: /run/secrets/genieacs_api_key
      FRONTEND_ORIGINS: http://localhost:1234,http://127.0.0.1:1234
    secrets:
      - genieacs_api_key
    ports:
      - "127.0.0.1:8000:8000"   # backend exposto só local
    networks:
      - genieacs_net
    volumes:
      - ./backend/genieacs_backend_mvp.py:/app/genieacs_backend_mvp.py:ro

  #############################################################################
  # Túnel público para o CWMP (7547) – ngrok                                  #
  # Gera uma URL HTTPS pública -> encaminha p/ http://genieacs:7547           #
  #############################################################################
  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok-acs
    restart: unless-stopped
    depends_on:
      - genieacs
    environment:
      NGROK_AUTHTOKEN: "${NGROK_AUTHTOKEN}"   # obrigatório (crie .env)
    command: ["http", "--log=stdout", "genieacs:7547"]  # forma em array (compatível)
    networks:
      - genieacs_net
    ports:
      - "4040:4040"                           # dashboard/API p/ ler a public_url

###############################################################################
# Volumes e rede                                                              #
###############################################################################
volumes:
  data_db:
  data_configdb:

networks:
  genieacs_net:
    driver: bridge

secrets:
  genieacs_api_key:
    file: ./secrets/genieacs_api_key.txt